default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: euglena_development
test:
  <<: *default
  database: euglena_test
production:
  <<: *default
  database: euglena_production
#  username: euglena
#  password: <%= ENV['EUGLENA_DATABASE_PASSWORD'] %>
